export interface Video {
  id: string;
  name: string;
  duration: number;
  type?: 'VOD' | 'Event' | 'Live' | 'YouTube';
  playlistName?: string;
  source?: 'playlist' | 'custom';
}

export const defaultPlaylistContent: Video[] = [
  { id: 'vod-1', name: 'Action Movie Collection', duration: 120, type: 'VOD', source: 'playlist' },
  { id: 'vod-2', name: 'Comedy Special', duration: 90, type: 'VOD', source: 'playlist' },
  { id: 'vod-3', name: 'Documentary Series', duration: 60, type: 'VOD', source: 'playlist' },
  { id: 'vod-4', name: 'Romantic Drama', duration: 110, type: 'VOD', source: 'playlist' },
  { id: 'vod-5', name: 'Thriller Night', duration: 95, type: 'VOD', source: 'playlist' },
  { id: 'vod-6', name: 'Family Adventure', duration: 100, type: 'VOD', source: 'playlist' },
  { id: 'vod-7', name: 'Sci-Fi Classic', duration: 130, type: 'VOD', source: 'playlist' },
  { id: 'vod-8', name: 'Horror Showcase', duration: 85, type: 'VOD', source: 'playlist' },
  { id: 'vod-9', name: 'Musical Extravaganza', duration: 140, type: 'VOD', source: 'playlist' },
  { id: 'vod-10', name: 'Crime Investigation', duration: 75, type: 'VOD', source: 'playlist' },
  { id: 'vod-11', name: 'Fantasy Quest', duration: 125, type: 'VOD', source: 'playlist' },
  { id: 'vod-12', name: 'Sports Documentary', duration: 55, type: 'VOD', source: 'playlist' },
  { id: 'vod-13', name: 'Historical Drama', duration: 105, type: 'VOD', source: 'playlist' },
  { id: 'vod-14', name: 'Animation Collection', duration: 80, type: 'VOD', source: 'playlist' },
  { id: 'vod-15', name: 'Mystery Thriller', duration: 115, type: 'VOD', source: 'playlist' },
  { id: 'vod-16', name: 'Comedy Stand-up', duration: 65, type: 'VOD', source: 'playlist' },
  { id: 'vod-17', name: 'Adventure Series', duration: 135, type: 'VOD', source: 'playlist' },
  { id: 'vod-18', name: 'Drama Series', duration: 70, type: 'VOD', source: 'playlist' },
  { id: 'vod-19', name: 'Action Thriller', duration: 95, type: 'VOD', source: 'playlist' },
  { id: 'vod-20', name: 'Romantic Comedy', duration: 90, type: 'VOD', source: 'playlist' },
  { id: 'vod-21', name: 'Superhero Saga', duration: 150, type: 'VOD', source: 'playlist' },
  { id: 'vod-22', name: 'War Documentary', duration: 85, type: 'VOD', source: 'playlist' },
  { id: 'vod-23', name: 'Nature Special', duration: 60, type: 'VOD', source: 'playlist' },
  { id: 'vod-24', name: 'Music Concert', duration: 120, type: 'VOD', source: 'playlist' },
  { id: 'vod-25', name: 'Comedy Movie', duration: 100, type: 'VOD', source: 'playlist' },
  { id: 'vod-26', name: 'Drama Film', duration: 110, type: 'VOD', source: 'playlist' },
  { id: 'vod-27', name: 'Action Blockbuster', duration: 140, type: 'VOD', source: 'playlist' },
  { id: 'vod-28', name: 'Thriller Series', duration: 75, type: 'VOD', source: 'playlist' },
  { id: 'vod-29', name: 'Romance Collection', duration: 95, type: 'VOD', source: 'playlist' },
  { id: 'vod-30', name: 'Horror Classic', duration: 80, type: 'VOD', source: 'playlist' },
  { id: 'vod-31', name: 'Sci-Fi Adventure', duration: 125, type: 'VOD', source: 'playlist' },
  { id: 'vod-32', name: 'Family Movie', duration: 105, type: 'VOD', source: 'playlist' },
  { id: 'vod-33', name: 'Comedy Series', duration: 65, type: 'VOD', source: 'playlist' },
  { id: 'vod-34', name: 'Drama Special', duration: 90, type: 'VOD', source: 'playlist' },
  { id: 'vod-35', name: 'Action Series', duration: 115, type: 'VOD', source: 'playlist' },
  { id: 'vod-36', name: 'Documentary Film', duration: 70, type: 'VOD', source: 'playlist' },
  { id: 'vod-37', name: 'Musical Drama', duration: 130, type: 'VOD', source: 'playlist' },
  { id: 'vod-38', name: 'Crime Drama', duration: 85, type: 'VOD', source: 'playlist' },
  { id: 'vod-39', name: 'Fantasy Adventure', duration: 135, type: 'VOD', source: 'playlist' },
  { id: 'vod-40', name: 'Sports Movie', duration: 100, type: 'VOD', source: 'playlist' },
  { id: 'vod-41', name: 'Historical Film', duration: 120, type: 'VOD', source: 'playlist' },
  { id: 'vod-42', name: 'Animation Movie', duration: 95, type: 'VOD', source: 'playlist' },
  { id: 'vod-43', name: 'Mystery Series', duration: 75, type: 'VOD', source: 'playlist' },
  { id: 'vod-44', name: 'Comedy Special', duration: 60, type: 'VOD', source: 'playlist' },
  { id: 'vod-45', name: 'Adventure Movie', duration: 110, type: 'VOD', source: 'playlist' },
  { id: 'vod-46', name: 'Drama Series', duration: 80, type: 'VOD', source: 'playlist' },
  { id: 'vod-47', name: 'Action Adventure', duration: 125, type: 'VOD', source: 'playlist' },
  { id: 'vod-48', name: 'Romantic Drama', duration: 90, type: 'VOD', source: 'playlist' },
  { id: 'vod-49', name: 'Superhero Movie', duration: 145, type: 'VOD', source: 'playlist' },
  { id: 'vod-50', name: 'War Film', duration: 140, type: 'VOD', source: 'playlist' },
  { id: 'vod-51', name: 'Nature Documentary', duration: 55, type: 'VOD', source: 'playlist' },
  { id: 'vod-52', name: 'Music Video Collection', duration: 65, type: 'VOD', source: 'playlist' },
  { id: 'vod-53', name: 'Comedy Movie Night', duration: 105, type: 'VOD', source: 'playlist' },
  { id: 'vod-54', name: 'Drama Feature', duration: 115, type: 'VOD', source: 'playlist' },
  { id: 'vod-55', name: 'Action Packed', duration: 95, type: 'VOD', source: 'playlist' },
  { id: 'vod-56', name: 'Thriller Night', duration: 85, type: 'VOD', source: 'playlist' },
  { id: 'vod-57', name: 'Romance Special', duration: 100, type: 'VOD', source: 'playlist' },
  { id: 'vod-58', name: 'Horror Night', duration: 90, type: 'VOD', source: 'playlist' },
  { id: 'vod-59', name: 'Sci-Fi Collection', duration: 130, type: 'VOD', source: 'playlist' },
  { id: 'vod-60', name: 'Family Fun', duration: 80, type: 'VOD', source: 'playlist' },
  { id: 'vod-61', name: 'Comedy Hour', duration: 70, type: 'VOD', source: 'playlist' },
  { id: 'vod-62', name: 'Drama Night', duration: 110, type: 'VOD', source: 'playlist' },
  { id: 'vod-63', name: 'Action Thrills', duration: 120, type: 'VOD', source: 'playlist' },
  { id: 'vod-64', name: 'Documentary Special', duration: 75, type: 'VOD', source: 'playlist' },
  { id: 'vod-65', name: 'Musical Night', duration: 135, type: 'VOD', source: 'playlist' },
  { id: 'vod-66', name: 'Crime Story', duration: 95, type: 'VOD', source: 'playlist' },
  { id: 'vod-67', name: 'Fantasy Quest', duration: 125, type: 'VOD', source: 'playlist' },
  { id: 'vod-68', name: 'Sports Action', duration: 85, type: 'VOD', source: 'playlist' },
  { id: 'vod-69', name: 'Historical Epic', duration: 150, type: 'VOD', source: 'playlist' },
  { id: 'vod-70', name: 'Animation Fun', duration: 90, type: 'VOD', source: 'playlist' },
  { id: 'vod-71', name: 'Mystery Thriller', duration: 105, type: 'VOD', source: 'playlist' },
  { id: 'vod-72', name: 'Comedy Gold', duration: 65, type: 'VOD', source: 'playlist' },
  { id: 'vod-73', name: 'Adventure Quest', duration: 140, type: 'VOD', source: 'playlist' },
  { id: 'vod-74', name: 'Drama Classic', duration: 100, type: 'VOD', source: 'playlist' },
  { id: 'vod-75', name: 'Action Hero', duration: 115, type: 'VOD', source: 'playlist' },
  { id: 'vod-76', name: 'Documentary Insight', duration: 60, type: 'VOD', source: 'playlist' },
  { id: 'vod-77', name: 'Musical Magic', duration: 120, type: 'VOD', source: 'playlist' },
  { id: 'vod-78', name: 'Crime Investigation', duration: 80, type: 'VOD', source: 'playlist' },
  { id: 'vod-79', name: 'Fantasy World', duration: 130, type: 'VOD', source: 'playlist' },
  { id: 'vod-80', name: 'Sports Highlights', duration: 70, type: 'VOD', source: 'playlist' },
  { id: 'vod-81', name: 'Historical Journey', duration: 110, type: 'VOD', source: 'playlist' },
  { id: 'vod-82', name: 'Animation Adventure', duration: 95, type: 'VOD', source: 'playlist' },
  { id: 'vod-83', name: 'Mystery Case', duration: 75, type: 'VOD', source: 'playlist' },
  { id: 'vod-84', name: 'Comedy Show', duration: 85, type: 'VOD', source: 'playlist' },
  { id: 'vod-85', name: 'Adventure Series', duration: 125, type: 'VOD', source: 'playlist' },
  { id: 'vod-86', name: 'Drama Series', duration: 90, type: 'VOD', source: 'playlist' },
  { id: 'vod-87', name: 'Action Blockbuster', duration: 145, type: 'VOD', source: 'playlist' },
  { id: 'vod-88', name: 'Thriller Series', duration: 100, type: 'VOD', source: 'playlist' },
  { id: 'vod-89', name: 'Romance Collection', duration: 105, type: 'VOD', source: 'playlist' },
  { id: 'vod-90', name: 'Horror Collection', duration: 80, type: 'VOD', source: 'playlist' },
  { id: 'vod-91', name: 'Sci-Fi Series', duration: 135, type: 'VOD', source: 'playlist' },
  { id: 'vod-92', name: 'Family Collection', duration: 95, type: 'VOD', source: 'playlist' },
  { id: 'vod-93', name: 'Comedy Collection', duration: 70, type: 'VOD', source: 'playlist' },
  { id: 'vod-94', name: 'Drama Collection', duration: 115, type: 'VOD', source: 'playlist' },
  { id: 'vod-95', name: 'Action Collection', duration: 120, type: 'VOD', source: 'playlist' },
  { id: 'vod-96', name: 'Documentary Collection', duration: 65, type: 'VOD', source: 'playlist' },
  { id: 'vod-97', name: 'Musical Collection', duration: 140, type: 'VOD', source: 'playlist' },
  { id: 'vod-98', name: 'Crime Collection', duration: 85, type: 'VOD', source: 'playlist' },
  { id: 'vod-99', name: 'Fantasy Collection', duration: 130, type: 'VOD', source: 'playlist' },
  { id: 'vod-100', name: 'Sports Collection', duration: 75, type: 'VOD', source: 'playlist' },
  { id: 'vod-101', name: 'Historical Collection', duration: 125, type: 'VOD', source: 'playlist' },
  { id: 'vod-102', name: 'Animation Collection', duration: 90, type: 'VOD', source: 'playlist' },
  { id: 'vod-103', name: 'Mystery Collection', duration: 105, type: 'VOD', source: 'playlist' },
  { id: 'vod-104', name: 'Comedy Special Collection', duration: 60, type: 'VOD', source: 'playlist' },
  { id: 'vod-105', name: 'Adventure Collection', duration: 135, type: 'VOD', source: 'playlist' }
].map(item => ({
  ...item,
  source: 'playlist' as const,
  playlistName: 'Default Playlist'
}));
